=== opendaylight/openflowplugin/openflowjava/simple-client/src/main/resources/scenario.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="eventType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sleepEvent"/>
            <xs:enumeration value="waitForMessageEvent"/>
            <xs:enumeration value="sendEvent"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="bytes">
        <xs:list itemType="xs:short"/>
    </xs:simpleType>

    <xs:complexType name="step">
        <xs:sequence>
            <xs:element name="order" type="xs:short" minOccurs="1" maxOccurs="1"/>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="event" type="eventType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="bytes" type="bytes" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="scenario">
        <xs:sequence>
            <xs:element name="step" type="step" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:element name="scenarios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="scenario" type="scenario" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== opendaylight/openflowplugin/openflowjava/simple-client/src/main/resources/scenario.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<scenarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scenario.xsd">
  <scenario name="handshakeScenarioWithBarrier">
    <step>
      <order>1</order>
      <name>send Hello</name>
      <event>sendEvent</event>
      <bytes>04 00 00 08 00 00 00 01</bytes>
    </step>
    <step>
      <order>2</order>
      <name>wait for Hello_21</name>
      <event>waitForMessageEvent</event>
      <bytes>04 00 00 10 00 00 00 15 00 01 00 08 00 00 00 12</bytes>
    </step>
    <step>
      <order>3</order>
      <name>wait for features request</name>
      <event>waitForMessageEvent</event>
      <bytes>04 05 00 08 00 00 00 02</bytes>
    </step>
    <step>
      <order>4</order>
      <name>features reply</name>
      <event>sendEvent</event>
      <bytes>04 06 00 20 00 00 00 02 00 01 02 03 04 05 06 07 00 01 02 03 01 00 00 00 00 01 02 03 00 01 02 03</bytes>
    </step>
    <step>
      <order>5</order>
      <name>wait for barrier</name>
      <event>waitForMessageEvent</event>
      <bytes>04 14 00 08 00 00 00 00</bytes>
    </step>
    <step>
      <order>6</order>
      <name>barrier reply</name>
      <event>sendEvent</event>
      <bytes>04 15 00 08 00 00 00 04</bytes>
    </step>
  </scenario>
</scenarios>
